# for running streamlit - assumes ollama already running
FROM python:3.9-slim

# Set a working directory in the container
WORKDIR /app

# Copy the local contents into the container at /app
COPY . /app

# Install Streamlit and any other dependencies you might have in a requirements.txt
RUN pip install --no-cache-dir streamlit


# Expose port 8501 for Streamlit
EXPOSE 8501

# Specify the entrypoint command
ENTRYPOINT ["streamlit", "run"]

# Default file to run with Streamlit if no arguments are provided to `docker run`
CMD ["streamlit.py"]
